baseURL = ''
languageCode = 'ja'
title = 'まさるの勉強部屋 ハンズオンチーム'
theme = 'hugo-theme-relearn'

[outputs]
  home = ['html', 'rss', 'search', 'searchpage'] # 検索機能オプション

[params]
  themeVariant = ['relearn-light', 'relearn-dark', 'auto']