baseURL = 'https://masaru-study.github.io/verify-note/'
languageCode = 'ja'
title = 'まさるの勉強部屋 ハンズオンチーム'
paginate = "3"
theme = 'mainroad'

[params]
  subtitle = 'The TEST subtitle'
  readmore = true  # 記事を一括表示しない
  toc = true  # 記事内での目次作成

[Params.sidebar]
  home = "right"  # トップページのサイドバーの場所
  list = "right"  # 記事一覧ページのサイドバーの場所
  single = "right"  # 記事ページのサイドバーの場所
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5  # 最新投稿の記事数
  categories_counter = true  # カテゴリー内の記事数
  tags_counter = true  # タグの記事数

[Params.widgets.social]
  github = "masaru-study/verify-note"

[[Menus.main]]
  Name = "トップ"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "カテゴリー"
  URL = "/categories/"
  weight = 2

[[Menus.main]]
  Name = "タグ"
  URL = "/tags/"
  weight = 3

