baseURL = 'https://masaru-study.github.io/verify-note/'
languageCode = 'ja'
title = 'まさるの勉強部屋 ハンズオンチーム'
theme = 'mainroad'
[params]
  subtitle = 'The TEST subtitle'
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist"]
