name: BUILD-DEPLIY-NOTIFICATION

# トリガー
on:
  push:
    branches:
      - main
  workflow_dispatch:

# GitHub Pagesに更新するためのGITHUB_TOKEN権限
permissions:
  contents: read
  pages: write
  id-token: write

# 同時デプロイ防止してスキップする。
# ただし実行中デプロイはキャンセルしない。
concurrency:
  group: "pages"
  cancel-in-progress: false

# Github Runnerのシェル
defaults:
  run:
    shell: bash

jobs:
  # ビルドジョブ
  build:
    # ジョブに必要な定義
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.125.4

    # Discord通知有無を別jobに渡す
    outputs:
      skip_notification: ${{ steps.decision.outputs.skip_notification }}

    steps:
      # ブランチの内容をチェックアウト（ダウンロード）する
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 記事の必須要件をチェック。
      - name: Front Matter check
        run: |
          er_cnt=0
          # _index.md以外の記事には、Authorタグが含まれている。
          for file in $(find ./content/ -name '*.md' | sed -e "/_index.md/d"); do
            tag_author=$(cat $file | sed -ne "/tags \= \[/p" | sed -ne "/Author:/p")
            if [ -z "$tag_author" ]; then
              echo "::error:: No Tag \"Author\": $file"
              er_cnt=$(expr $er_cnt + 1)
            fi
          done
          # _index.md以外またはGeneral、Otherカテゴリ以外の記事には、Levelタグが含まれている。
          for file in $(find ./content/ -name '*.md' | sed -e "/_index.md/d" | sed -e "/content\/general/d" | sed -e "/content\/other/d"); do
            tag_level=$(cat $file | sed -ne "/tags \= \[/p" | sed -ne "/Level:/p")
            if [ -z "$tag_level" ]; then
              echo "::error:: No Tag \"Level\": $file"
              er_cnt=$(expr $er_cnt + 1)
            fi
          done
          if [ $er_cnt -eq 0 ]; then exit 0; else exit 1; fi

      # ルートディレクトリにno_discord.txtがあるか確認。
      - name: Check notification no_file
        id: no_file
        uses: andstor/file-existence-action@v3
        with:
          files: ./no_discord.txt

      # Merge Messageの本文内にno_discordが含まれているか確認。
      - name: Check notification no_message
        id: no_message
        run: |
          if [ -n "$(echo "${{ github.event.head_commit.message }}" | sed -ne "/[Nn][Oo]_[Dd][Ii][Ss][Cc][Oo][Rr][Dd]/p")" ]; then
            echo "message_exists=true" >> $GITHUB_OUTPUT
          else
            echo "message_exists=false" >> $GITHUB_OUTPUT
          fi

      # 通知条件の判断結果を出力。
      - name: Decision notification
        id: decision
        run: |
          if [ ${{ steps.no_file.outputs.files_exists }} = 'true' ] || [ ${{ steps.no_message.outputs.message_exists }} = 'true' ]; then
            echo "skip_notification=true" >> $GITHUB_OUTPUT
          else
            echo "skip_notification=false" >> $GITHUB_OUTPUT
          fi

      # Hugoのインストール
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # Hugo依存関係パッケージのインストール
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      # Github Pagesを設定
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # Github Pages依存関係パッケージのインストール
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      # Hugoでビルドする
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          TZ: Asia/Tokyo
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      # ビルドした結果をアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # デプロイジョブ
  deploy:
    # ジョブに必要な定義
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # ビルドした結果をデプロイ
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Discord通知ジョブ-ステージング環境用
  Notification-Staging:
    # ジョブに必要な定義
    runs-on: ubuntu-latest
    needs: deploy

    # 通知条件を満たしていない場合はジョブ自体をスキップ。
    if: needs.build.outputs.skip_notification != 'true' && github.repository == 'masaru-study/-----test-----verify-note'

    steps:
      # Discord通知内容を格納
      - name: Notification message create
        id: message
        run: |
          {
            echo 'TEXT<<EOF'
            echo "${{ github.event.head_commit.author.name }} がページを更新しました。"
            echo "$(echo "${{ github.event.head_commit.message }}" | sed -e "1,2d")"
            echo "https://masaru-study.github.io/verify-note/"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      # Discord通知を実施。
      - name: Send Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_STAGING }}
          DISCORD_USERNAME: "ハンズオンチーム"
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ${{ steps.message.outputs.text }}

  # Discord通知ジョブ-本番環境用
  Notification-Prod:
    # ジョブに必要な定義
    runs-on: ubuntu-latest
    needs: deploy
    if: needs.build.outputs.skip_notification != 'true' && github.repository == 'masaru-study/verify-note'

    steps:
      # Discord通知内容を格納
      - name: Notification message create
        id: message
        run: |
          {
            echo 'TEXT<<EOF'
            echo "${{ github.event.head_commit.author.name }} がページを更新しました。"
            echo "$(echo "${{ github.event.head_commit.message }}" | sed -e "1,2d")"
            echo "https://masaru-study.github.io/verify-note/"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      # Discord通知を実施。
      - name: Send Discord
        env:
          ISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_NOTICE }}
          DISCORD_USERNAME: "ハンズオンチーム"
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ${{ steps.message.outputs.text }}
